<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductDetail', 'doctrine');

/**
 * BaseProductDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property integer $product_detail_type_id
 * @property string $val
 * 
 * @method integer       getId()                     Returns the current record's "id" value
 * @method integer       getProductId()              Returns the current record's "product_id" value
 * @method integer       getProductDetailTypeId()    Returns the current record's "product_detail_type_id" value
 * @method string        getVal()                    Returns the current record's "val" value
 * @method ProductDetail setId()                     Sets the current record's "id" value
 * @method ProductDetail setProductId()              Sets the current record's "product_id" value
 * @method ProductDetail setProductDetailTypeId()    Sets the current record's "product_detail_type_id" value
 * @method ProductDetail setVal()                    Sets the current record's "val" value
 * 
 * @package    megamed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_detail');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_detail_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('val', 'string', 155, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 155,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}