<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserCredentials', 'doctrine');

/**
 * BaseUserCredentials
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $credential
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method integer         getUserId()     Returns the current record's "user_id" value
 * @method string          getCredential() Returns the current record's "credential" value
 * @method UserCredentials setId()         Sets the current record's "id" value
 * @method UserCredentials setUserId()     Sets the current record's "user_id" value
 * @method UserCredentials setCredential() Sets the current record's "credential" value
 * 
 * @package    megamed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserCredentials extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_credentials');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('credential', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}