<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrderProducts', 'doctrine');

/**
 * BaseOrderProducts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $order_id
 * @property integer $product_id
 * @property integer $quantity
 * @property float $price
 * @property float $amount
 * 
 * @method integer       getId()         Returns the current record's "id" value
 * @method integer       getOrderId()    Returns the current record's "order_id" value
 * @method integer       getProductId()  Returns the current record's "product_id" value
 * @method integer       getQuantity()   Returns the current record's "quantity" value
 * @method float         getPrice()      Returns the current record's "price" value
 * @method float         getAmount()     Returns the current record's "amount" value
 * @method OrderProducts setId()         Sets the current record's "id" value
 * @method OrderProducts setOrderId()    Sets the current record's "order_id" value
 * @method OrderProducts setProductId()  Sets the current record's "product_id" value
 * @method OrderProducts setQuantity()   Sets the current record's "quantity" value
 * @method OrderProducts setPrice()      Sets the current record's "price" value
 * @method OrderProducts setAmount()     Sets the current record's "amount" value
 * 
 * @package    megamed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrderProducts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('order_products');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('amount', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}