# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

#product
product_new:
  url:   /admin/product-new
  param: { module: product, action: new }

product_edit:
  url:   /admin/product-edit
  param: { module: product, action: edit }

product:
  url:   /admin/product
  param: { module: product, action: index }

#login
login:
  url:   /admin/login
  param: { module: user, action: login }

#logout
logout:
  url:   /admin/logout
  param: { module: user, action: logout }

# default rules
homepage:
  url:   /admin
  param: { module: dashboard, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
