<?php

/**
 * OrderProductDetailsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrderProductDetailsTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object OrderProductDetailsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OrderProductDetails');
    }

    public static function getDetails($orderProductId)
    {
        $sql = 'SELECT t.name, d.val
                FROM order_product_details d
                LEFT JOIN product_detail_type t ON t.id = d.product_detail_type_id
                WHERE order_product_id = ' . (int) $orderProductId;
        
        $pdo = Doctrine_Manager::connection()->getDbh();
        $rows = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);

        $html = '';
        foreach ($rows as $row) {
            $html .= $row['name'] . ': ' . $row['val'];
            $html .='<br/>';
        }

        return $html;
    }

}
