<?php

/**
 * OrdersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OrdersTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object OrdersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Orders');
    }

    public static function getList()
    {
        $rows = self::getInstance()
                ->createQuery()
                ->orderBy('status')
                ->fetchArray();

        return $rows;
    }

    public static function getMy($userId)
    {
        $rows = self::getInstance()
                ->createQuery()
                ->where('user_id <> 0')
                ->andWhere('user_id = ?', $userId)
                ->orderBy('status')
                ->fetchArray();

        return $rows;
    }

}
