<?php

/**
 * ProductDetailTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductDetailTypeTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object ProductDetailTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductDetailType');
    }

    public static function getList()
    {
        $rows = self::getInstance()
                ->createQuery()
                ->fetchArray();

        return $rows;
    }

    public static function getForSelect()
    {
        $rows = self::getInstance()
                ->createQuery()
                ->fetchArray();

        $arr = array();
        foreach ($rows as $row) {
            $arr[$row['id']] = $row['name'];
        }

        return $arr;
    }

}
