<?php

/**
 * ProductDetailTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductDetailTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductDetailTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductDetailType');
    }
}