<?php

/**
 * ProductDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductDetailTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object ProductDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductDetail');
    }

    public static function getList($productId)
    {
        $rows = self::getInstance()
                ->createQuery()
                ->where('product_id = ?', $productId)
                ->fetchArray();

        return $rows;
    }

}
