<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }

    public static function getList()
    {
        $sql = 'SELECT c.`name` AS category_name, p.*
                FROM product p
                LEFT JOIN category c ON c.id = p.category_id
                WHERE p.is_active = 1';

        $pdo = AppEntity::getConnection();
        $rows = $pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC);

        return $rows;
    }

}
