<?php

/**
 * UserFbTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserFbTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserFbTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserFb');
    }
}