<?php

/**
 * UserCredentialsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCredentialsTable extends Doctrine_Table
{

    /**
     * Returns an instance of this class.
     *
     * @return object UserCredentialsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserCredentials');
    }

    public static function getBy($userId)
    {
        $rows = self::getInstance()
                ->createQuery()
                ->where('user_id = ?', $userId)
                ->fetchArray();

        return $rows;
    }

}
