# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

ship:
  url:   /ship
  param: { module: ship, action: index }

order_my:
  url:   /order-my
  param: { module: orders, action: my }

order_update:
  url:   /order-update
  param: { module: orders, action: update }

order_products:
  url:   /order-products
  param: { module: orders, action: products }

orders:
  url:   /orders
  param: { module: orders, action: index }

manage_product_delete:
  url:   /manage-product-delete
  param: { module: manageProduct, action: delete }

manage_product_update:
  url:   /manage-product-update
  param: { module: manageProduct, action: update }

manage_product_create:
  url:   /manage-product-create
  param: { module: manageProduct, action: create }

manage_product_new:
  url:   /manage-product-new
  param: { module: manageProduct, action: new }

manage_product_edit:
  url:   /manage-product-edit
  param: { module: manageProduct, action: edit }

manage_product:
  url:   /manage-product
  param: { module: manageProduct, action: index }

cart_check_complete:
  url:   /cart-check-complete
  param: { module: cart, action: complete }

cart_check:
  url:   /cart-check
  param: { module: cart, action: check }

cart_view:
  url:   /cart-view
  param: { module: cart, action: view }

cart_delete:
  url:   /cart-delete
  param: { module: cart, action: delete }

cart_add:
  url:   /cart-add
  param: { module: cart, action: add }

cart:
  url:   /cart
  param: { module: cart, action: index }

# default rules
contact:
  url:   /contact
  param: { module: contact, action: index }

about:
  url:   /about
  param: { module: about, action: index }

news_detail:
  url:   /news/:id
  param: { module: news, action: detail }

news:
  url:   /news
  param: { module: news, action: index }

product_detail:
  url:   /product-detail/:id
  param: { module: product, action: detail }

product:
  url:   /product
  param: { module: product, action: index }

logout:
  url:   /logout
  param: { module: public, action: logout }

login:
  url:   /login
  param: { module: public, action: login }

homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
