all:
  metas:
    title:        Бүтээгдэхүүн

newSuccess:
  stylesheets:    []
  javascripts:    [ckeditor/ckeditor.js, ckfinder/ckfinder.js]

editSuccess:
  stylesheets:    []
  javascripts:    [ckeditor/ckeditor.js, ckfinder/ckfinder.js]