all:  
  has_layout:     true
  layout:         login
  
loginSuccess:
  stylesheets:    []
  javascripts:    [login/login.js]
  
secureSuccess:
  has_layout:     true
  layout:         layout